# Source: jx-build-controller/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-x-controllerbuild
  labels:
    app: jx-build-controller
    chart: jx-build-controller-0.5.19
    release: jx-build-controller
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::474668408945:role/jx-labs-build-ctrl
    meta.helm.sh/release-name: 'jx-build-controller'
    meta.helm.sh/release-namespace: 'jx'
  namespace: jx
