apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: jx-labs
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "474668408945"
    provider: eks
    region: us-east-1
    registry: 474668408945.dkr.ecr.us-east-1.amazonaws.com
  environments:
  - key: dev
    owner: josias-mk-organisation
    repository: cluster-jx-labs-dev
  - key: staging
  - key: production
  ingress:
    domain: 18.204.73.49.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    email: jmroboot@gmail.com
    username: jmroboot
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: s3://logs-jx-labs-20250317234705891200000013
  - name: reports
    url: s3://reports-jx-labs-20250317234705891200000012
  - name: repository
    url: s3://repository-jx-labs-20250317234705891200000014
  terraform: true
  vault: {}
  webhook: lighthouse
